"use client";

import Softwares from "@/components/Pages/Softwares/Softwares/Softwares";
import SearchBar from "@/components/global/SearchBar/SearchBar";
import Spinner from "@/components/global/Spinner/Spinner";
import React, { useEffect, useState } from "react";


export const metadata = {
  title: "Softwares | PC-HUB BD",
  description: "Generated by create next app",
};

const SoftwaresPage = () => {
  const [searchKey, setSearchKey] = useState('');
  const [filteredSoftwares, setFilteredSoftwares] = useState([]);
  const [allSoftwares, setAllSoftwares] = useState([]);

  useEffect(() => {
    fetch('/softwares.json')
      .then(res => res.json())
      .then(data => setAllSoftwares(data))
  }, [])

  useEffect(() => {
    setFilteredSoftwares(allSoftwares)
  }, [allSoftwares])



  // Search submit
  const handleSearchBar = (e) => {
    e.preventDefault();
    handleSearchResults();
  };


  // Search for software by category
  const handleSearchResults = () => {
    // console.log(searchKey.length);
    if (searchKey.length > 0) {
      const result = allSoftwares?.filter((software) =>
        software?.category.toLowerCase().includes(searchKey.toLowerCase().trim()) ||
        software?.name.toLowerCase().includes(searchKey.toLowerCase().trim())
      );
      setFilteredSoftwares(result);
    } else {
      setFilteredSoftwares(allSoftwares)
    }

  };

  // Clear search and show all blogs
  const handleClearSearch = () => {
    setSearchKey('');
    // console.log("clear");
    setFilteredSoftwares(allSoftwares);
  };
  return (
    <div className="">

      {/* Search Bar */}
      <SearchBar
        value={searchKey}
        clearSearch={handleClearSearch}
        formSubmit={handleSearchBar}
        handleSearchKey={(e) => setSearchKey(e.target.value)}
      />

      {/* Softwares List & Empty View */}
      {!filteredSoftwares?.length ? <Spinner /> : <Softwares softwares={filteredSoftwares} />}
    </div>
  );
};

export default SoftwaresPage;
