import React from "react";


export const metadata = {
  title: "Softwares | PC-HUB BD",
  description: "Generated by create next app",
};

const SoftwaresPage = () => {
  return (
    <>

    </>
  );
};

export default SoftwaresPage;
