import ContactUsBanner from "@/components/pages/ContactUs/ContactUsBanner";
import ContactForm from "@/components/pages/ContactUs/ContactForm";
import ContactUsSide from "@/components/pages/ContactUs/ContactUsSide";
import React from "react";
import ContactUsFindOurLocation from "@/components/pages/ContactUs/ContactUsFindOurLocation";
import ContactUsMap from "@/components/pages/ContactUs/UI/ContactUsMap";
import GetInTouch from "@/components/pages/ContactUs/GetInTouch";

export const metadata = {
  title: "Contact US | Digital Marketing Institute BD",
  description: "Generated by create next app",
};

const ContactUsPage = () => {
  return (
    <>
      {/* ......................banner...................  */}

      <ContactUsBanner />

      {/* ......................Contact Form...................  */}
      <div className=" grid grid-cols-1 lg:grid-cols-2 gap-20 lg:my-24 my-5  max-width">
        <ContactUsSide />
        <ContactForm />
      </div>
      {/* ......................Find Out Location...................  */}
      <div className=" my-10 ">
        <ContactUsFindOurLocation />
        <div className="max-width">
          <ContactUsMap />
        </div>
      </div>
      {/* ......................Get in touch...................  */}
      <GetInTouch />
    </>
  );
};

export default ContactUsPage;
