import React from "react";


export const metadata = {
  title: "Software Details | PC-HUB BD",
  description: "Generated by create next app",
};

const SoftwareDetailsPage = () => {
  return (
    <>

    </>
  );
};

export default SoftwareDetailsPage;
