import AboutUsBanner from "@/components/Pages/AboutUs/AboutUsBanner";
import CompanyHistory from "@/components/Pages/AboutUs/CompanyHistory";
import ImageTextLayout from "@/components/Pages/AboutUs/ImageTextLayout";
import OurPrinciple from "@/components/Pages/AboutUs/OurPrinciple";
import React from "react";

export const metadata = {
  title: "About US | Digital Marketing Institute BD",
  description: "Generated by create next app",
};

const AboutUsPage = () => {
  return <div>
    <AboutUsBanner />
    <CompanyHistory />
    <OurPrinciple />
    <ImageTextLayout />
  </div>;
};

export default AboutUsPage;
